#!/bin/bash

# This script compile the software für OBP60-S3

# Attention! Start this cript only in the Gitpod Docker container.
# Start the script with: bash run

# Compile the firmware
echo "Compiling Firmware"
platformio run -e obp60_s3